// apps/demo-react/src/App.tsx
import { useState } from 'react'
import {
  ALL_VARIANTS,
  PulseFab,
  PulsePlayer,
  usePulseAudio,
  type PulseVariant,
} from '@pulse-music/react'
import { demoTracks } from '../../shared-tracks'

const tracks = demoTracks()

export function App() {
  const [variant, setVariant] = useState<PulseVariant>('auto')
  const [events, setEvents] = useState<string[]>([])
  const { isPlaying, track, currentTime, duration, fmt, toggle } = usePulseAudio()
  const log = (line: string) => setEvents((prev) => [line, ...prev].slice(0, 6))

  return (
    <main>
      <h1>Pulse × React</h1>
      <div className="picker" role="group" aria-label="Theme">
        {ALL_VARIANTS.filter((v) => v !== 'custom').map((v) => (
          <button key={v} aria-pressed={variant === v} onClick={() => setVariant(v)}>
            {v}
          </button>
        ))}
      </div>

      <PulsePlayer
        variant={variant}
        tracks={tracks}
        ambientEq
        onPlay={({ track }) => log(`play · ${track.title}`)}
        onPause={({ time }) => log(`pause · ${fmt(time)}`)}
        onTrackChange={({ track }) => log(`track · ${track.title}`)}
      />

      <p className="status">
        {/* Any component can read the shared session through the hook. */}
        <button onClick={toggle}>{isPlaying ? 'Pause' : 'Play'}</button> {track?.title} ·{' '}
        {fmt(currentTime)} / {fmt(duration)}
      </p>
      <ul className="log" aria-live="polite">
        {events.map((e, i) => (
          <li key={i}>{e}</li>
        ))}
      </ul>

      <PulseFab variant={variant} pulso />
    </main>
  )
}

// apps/demo-svelte/src/App.svelte
<script lang="ts">
  import { usePulseAudio, ALL_VARIANTS, type PulseVariant } from '@pulse-music/svelte'

  // Svelte 5 runes — the `usePulseAudio()` hook exposes a classic
  // store, so `$audio.isPlaying` auto-subscribes.
  const audio = usePulseAudio()
  let variant = $state<PulseVariant>('auto')
  let log = $state<string[]>([])

  function append(line: string) {
    log = [`[${new Date().toLocaleTimeString()}] ${line}`, ...log].slice(0, 40)
  }

  function onPlay(e: CustomEvent) {
    append(`pulse-play → ${e.detail.track.title}`)
  }
  function onPause(e: CustomEvent) {
    append(`pulse-pause → ${e.detail.track.title}`)
  }
  function onTrackChange(e: CustomEvent) {
    append(`pulse-trackchange → ${e.detail.from} → ${e.detail.to}`)
  }
</script>

<h1>Pulse — Svelte demo</h1>

<div class="picker" role="group" aria-label="Theme variant">
  {#each ALL_VARIANTS.filter((v) => v !== 'custom') as v}
    <button data-variant={v} aria-pressed={variant === v} onclick={() => (variant = v)}>
      {v}
    </button>
  {/each}
</div>

<div class="stage">
  <pulse-player
    variant={variant}
    ambient-eq
    onpulse-play={onPlay}
    onpulse-pause={onPause}
    onpulse-trackchange={onTrackChange}
  ></pulse-player>
</div>

<div class="controls">
  <button onclick={audio.prev}>⏮ Prev</button>
  <button onclick={audio.toggle}>{$audio.isPlaying ? '⏸ Pause' : '▶ Play'}</button>
  <button onclick={audio.next}>Next ⏭</button>
  <span class="stat">
    {audio.fmt($audio.currentTime)} / {audio.fmt($audio.duration)} · {$audio.track.title}
  </span>
</div>

<pulse-fab variant={variant} pulso></pulse-fab>

<div class="log" aria-live="polite">
  {#each log as line}
    <div>{line}</div>
  {/each}
</div>
